<<<<<<< HEAD
# Generated by Django 4.2.26 on 2026-01-19 04:11
=======
# Generated by Django 5.2.8 on 2026-01-16 12:23
>>>>>>> f08ccc7210252c2b5a9e087bf6b2db95b8751caf

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Tax'},
        ),
    ]
