# Generated by Django 5.2.8 on 2025-11-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='core/media/user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='core/media/user'),
        ),
    ]
