# Generated by Django 5.2.12 on 2026-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0007_alter_openinghour_from_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
