# Generated by Django 5.2.8 on 2026-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='amount',
            field=models.FloatField(default=123456),
            preserve_default=False,
        ),
    ]
