# Generated by Django 5.2.8 on 2026-01-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderedfood_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='tarnsaction_id',
            new_name='transaction_id',
        ),
    ]
