# Generated by Django 4.2.26 on 2026-02-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0007_alter_openinghour_from_hour_and_more'),
        ('orders', '0003_rename_tarnsaction_id_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='vendor_app.vendor'),
        ),
    ]
